model:
  max_iterations: 10
  # for Azure Open AI use azure/<azure-deployment-name>
  model: gpt-4o
  enable_multi_modal: false
  ollama_server_url: 'http://localhost:11434'

sample_prompts:
  prompts:
    - "What can you help me do?"
    - "Which tools do you have access to?"
    - "What are your capabilities?"

environment:
  type: dev

timeout:
  llm: 30

target_agent_id:
  max_iterations: 10
  model: claude-3-5-sonnet-20240620
  #model: gpt-3.5-turbo
  timeout: 15
  environment: dev
  enable_multi_modal: true
  ollama_server_url: 'http://123.456.78.90:11434'
  sample_prompts:
    prompts:
      - "What can you help me do?"
      - "Which tools do you have access to?"
      - "What are your capabilities?"
    
logging:
  log_file_path: swarmzero.log
  log_level: DEBUG
